### ISSUE TITLE
How can we async load zxcvbn?

### ISSUE THREAD

**Issue by elwayman02** [elwayman02/ember-cli-password-strength#1]
Would be nice to have a way to load this script asynchronously with the app rather than bundling it at compile time, since it's a hefty 3-600 kb (depending on gzip vs uncompressed).
##

**Comment by nickschot** [comment]
This is an old issue, but I think it's still relevant.

I've solved this slightly differently by creating a service which asynchronously loads the zxcvbn script by using `Ember.$.getScript`. Controllers/components which need zxcvbn will need to check if it's loaded or else call load on the service on init. 

Might be an applicable solution for people, but the approach is completely different from this addon (as it does not get "imported").

**Comment by JoshSmith** [comment]
I believe that we had do something similar in `ember-stripe-service` to lazy load in Stripe (because Stripe is hosted and must be loaded separately).

**Comment by jrjohnson** [comment]
I'm going to take a shot at this this week. @elwayman02 would you prefer we support both sync and async loading at the same time? Or would it make sense to make the a major BC break and only support async loading?  

Essentially I'm wondering if we need to add a config option to *not* include the JS initially or we can just assume it won't be and change the API for *strength()*?

This isn't completely the right approach, but there is some workable code at:
https://github.com/xurei/zxcvbn-async/blob/master/index.js

**Comment by elwayman02** [comment]
Hmm, it would be nice to support both sync and async, but I think realistically most apps are going to want async and will not need the library to be there immediately upon page load. So it seems fine to make a BC to async if supporting both is a pain.

**Comment by jrjohnson** [comment]
Alright. I took a shot at providing sync / async via two separate shims in #68. All feedback and lots of testing greatly appreciated.
