### ISSUE TITLE
Fingerprinting zxcvbn.js not working in bundle when bundleZxcvbn: false is set

### ISSUE THREAD

**Issue by chrisvdp** [elwayman02/ember-cli-password-strength#71]
I'm not sure if this belongs here or in ember-cli.

We side load zxcvbn.js via the `bundleZxcvbn: false` option.

Since our upgrade to Ember 3.1.4 we have lost fingerprinting on the zxcvbn.js file in the vendor.js that is generated via `ember build -prod`. The file itself that is placed in the root is fingerprinted, which results in a 404.

vendor.js shows
```js
...
const i=`${t.rootURL}zxcvbn.js`
...
```
the file on disk is 
`/zxcvbn-3b51ab340a2255ce5cc78168e81a483c.js`

Looking at our build artifacts I can see that this was working prior to our upgrade, but broke when we merged in our upgrade to 3.1.4 from 2.18.2

**Comment by jrjohnson** [comment]
@chrisvdp - thanks for the report. 

I'm not seeing this issue in our ember-cli 3.1.4 app. Can you try and reproduce this in a minimal new app to rule out anything else?

**Comment by chrisvdp** [comment]
Thanks for the quick reply! It ended up being an issue with our `config/targets.js` file.
